In [3]:
import torch
import torch.nn as nn

In [12]:
sentence = "I love cats"

In [19]:
words = sentence.split()
print(len(words))

3


In [22]:
seq_len = len(words) 
d_model = 512

### torch.zeros()
#### Write description of the method:

In [26]:
### I mada tensor 
pe = torch.zeros(seq_len, d_model)

In [27]:
pe

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [88]:
## This is to be added to the vector pe
position = torch.arange(0,seq_len,1)

In [89]:
position
print(position.shape)

torch.Size([3])


In [90]:
position = position.unsqueeze(1)
print(position.shape)

torch.Size([3, 1])


In [91]:
position

tensor([[0],
        [1],
        [2]])

In [104]:
a = torch.tensor([
    [4, 8 , 9],
    [3, 4 , 2]
    ])
print(a.shape)

torch.Size([2, 3])


In [109]:
random_list = torch.randn(5)
print(random_list)

tensor([-1.7931,  0.6723,  0.8576, -0.2851, -0.9955])


In [110]:
## Sin take the values in radian
## sin(radian values)
torch.sin(random_list)

tensor([-0.9754,  0.6228,  0.7563, -0.2813, -0.8391])

In [111]:
pe

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [112]:
position

tensor([[0],
        [1],
        [2]])

In [113]:
div_term = 7

In [136]:
(torch.sin(position * div_term)).shape


torch.Size([3, 1])

In [122]:
test=torch.tensor([[2,6,7],[3,9,0],[4,1,5]])
print(test)

tensor([[2, 6, 7],
        [3, 9, 0],
        [4, 1, 5]])


In [140]:
test[:,0::2] = torch.sin(position * div_term)
test[:,1::2] = torch.cos(position * div_term)

In [145]:
(test.unsqueeze(0))

tensor([[[0, 1, 0],
         [0, 0, 0],
         [0, 0, 0]]])

here
